# Generated by Django 5.2.10 on 2026-01-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationnote',
            options={},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CARE_PLAN', 'Care Plan'), ('RISK_ASSESSMENT', 'Risk Assessment'), ('CONSENT', 'Consent'), ('MEDICATION', 'Medication'), ('INCIDENT', 'Incident Report'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='service_user_docs/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='care.serviceuser')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
